version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: resort_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: resort_booking
      MYSQL_USER: resort_user
      MYSQL_PASSWORD: resort_pass
    ports:
      - "3307:3306"
    volumes:
      - resort_mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: resort_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  resort_mysql_data: